import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Form from "../Components/form";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rome Conversion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/colosseum.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Rome!</h1>
        <p>Convert or Compute any Number or Roman Numeral</p>
      </main>
      <Form />
    </div>
  );
}
