import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Form from "../Components/form";

export default function Home() {
  const [input, setInput] = useState();
  const [result, setResult] = useState();

  const handleSubmit = async (e) => {
    e.preventDefault();
    const response = await fetch("/api/conversionHandler", {
      method: "POST",
      body: JSON.stringify({ input }),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await response.json();
    setResult(data.result);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Rome Conversion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Rome!</h1>
        <p>Convert any Number or Roman Numeral</p>
      </main>
      <Form />
    </div>
  );
}
